[tool.poetry]
name = "pythonproject11"
version = "0.1.0"
description = ""
authors = ["Dell-PC <Igorek.kovalenko.2015@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
